#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module for Task Master Pro - 2026
# Generated by PAGE framework conventions with enhanced integration hooks

import sys
import os
import json
import tkinter as tk
import tkinter.ttk as ttk
from tkinter import messagebox, filedialog
import psutil
import webbrowser
import urllib.parse

# --------------------------------------------------------
# CORE PERSISTENCE CONFIGURATION MAPPINGS
# --------------------------------------------------------
CONFIG_FILE = "task_master_config.json"

# --------------------------------------------------------
# GLOBAL DATA REGISTRY STORAGE ARRAYS
# --------------------------------------------------------
system_whitelist = [
    "explorer.exe", 
    "taskmgr.exe", 
    "svchost.exe", 
    "python.exe",
    "TaskMasterPro.exe",    
    "cleaner.py"
]

game_exceptions = [
    "discord.exe", 
    "obs64.exe", 
    "steamwebhelper.exe"
]

scanned_junk_pool = []
scanned_safe_pool = []
installed_games_list = []  

# --------------------------------------------------------
# ENGINE BACKGROUND LIFECYCLE HANDLES
# --------------------------------------------------------
live_refresh_job = None
root = None

# --------------------------------------------------------
# PAGE FRAMEWORK INITIALIZATION INTERFACES
# --------------------------------------------------------
def main(*args):
    '''Main entry point for the application GUI framework loops.'''
    global root
    
    # High DPI Scaling Fix for Windows Executables
    try:
        import ctypes
        ctypes.windll.shcore.SetProcessDpiAwareness(2)
    except Exception:
        try:
            ctypes.windll.user32.SetProcessDPIAware()
        except Exception:
            pass

    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', on_closing)
    
    import cleaner
    global _top1, _w1
    _top1 = root
    _w1 = cleaner.Toplevel1(_top1)
    
    _w1.style = ttk.Style()
    init_backend_logic(_w1)
    root.mainloop()

def on_closing():
    '''Ensures non-blocking threads or loops are safely unhooked on exit.'''
    global live_refresh_job
    if live_refresh_job:
        root.after_cancel(live_refresh_job)
    root.destroy()

def init_backend_logic(gui_instance):
    '''Fires immediately post-compilation to establish local environments and bind UI commands.'''
    
    # Dashboard Control Component Bindings
    gui_instance.btn_scan.configure(command=lambda: handle_scan(gui_instance))
    gui_instance.btn_clean.configure(command=lambda: handle_clean(gui_instance))
    gui_instance.btn_kill.configure(command=lambda: handle_kill_selected(gui_instance))
    gui_instance.btn_Google.configure(command=lambda: google_selected_process(gui_instance))
    
    # Custom Whitelist Array Modification Connectors
    gui_instance.Button_Add.configure(command=lambda: add_whitelist_item(gui_instance))
    gui_instance.Button_Remove.configure(command=lambda: remove_whitelist_item(gui_instance))
    
    # Game Mode System Module Hooks
    gui_instance.btn_Scan_Games.configure(command=lambda: handle_game_scan(gui_instance))
    gui_instance.btn_Man_Games.configure(command=lambda: handle_manual_game_add(gui_instance))
    gui_instance.btn_Exception.configure(command=lambda: add_to_exceptions(gui_instance))
    gui_instance.btn_RemoveException.configure(command=lambda: remove_from_exceptions(gui_instance))
    gui_instance.btn_scanbackground.configure(command=lambda: handle_scan(gui_instance))
    
    # Settings Profile Management Operations
    gui_instance.btn_Apply.configure(command=lambda: save_config_state(gui_instance))
    gui_instance.btn_undo.configure(command=lambda: load_persistent_config(gui_instance))
    
    # Dropdown List Allocation Setup
    gui_instance.theme_dropdown['values'] = ("Dark Classic", "Light Modern", "Cyberpunk Amber")
    gui_instance.theme_dropdown.bind("<<ComboboxSelected>>", lambda e: apply_theme_change(gui_instance))

    # Treeview Columns Structure Allocation Loops
    for tree in [gui_instance.Scrolledtree_Safe, gui_instance.Scrolledtree_Junk, gui_instance.Scrolledtree_installed_games, gui_instance.Scrolledtree_BackGround]:
        tree.configure(columns=("PID", "RAM"))
        tree.heading("#0", text="Application / Game Name", anchor="w")
        tree.heading("PID", text="PID", anchor="center")
        tree.heading("RAM", text="Memory", anchor="center")
        tree.column("#0", width=180, stretch=True)
        tree.column("PID", width=60, anchor="center")
        tree.column("RAM", width=80, anchor="center")

    # Initial Loading Lifecycle Execution
    load_persistent_config(gui_instance)
    
    log_to_console(gui_instance, "System Initialization complete.")
    log_to_console(gui_instance, "Ready for system optimization check.")
    
    gui_instance.Scrolledtext_inspector.insert(tk.END, "Click 'Scan Active Processes' to analyze running process footprints.")

# --------------------------------------------------------
# DIAGNOSTIC ENGINE SYSTEM LOGIC
# --------------------------------------------------------
def log_to_console(gui, text_line):
    '''Helper to append timestamp lines straight into the Activity Console box.'''
    gui.Scrolledtext_console.configure(state=tk.NORMAL)
    gui.Scrolledtext_console.insert(tk.END, f">> {text_line}\n")
    gui.Scrolledtext_console.see(tk.END)
    gui.Scrolledtext_console.configure(state=tk.DISABLED)

def handle_scan(gui):
    '''Scans active Windows processes and splits them into lists based on the whitelist.'''
    global scanned_junk_pool, scanned_safe_pool
    
    scanned_junk_pool.clear()
    scanned_safe_pool.clear()
    
    for row in gui.Scrolledtree_Safe.get_children(): 
        gui.Scrolledtree_Safe.delete(row)
        
    for row in gui.Scrolledtree_Junk.get_children(): 
        gui.Scrolledtree_Junk.delete(row)

    for row in gui.Scrolledtree_BackGround.get_children():
        gui.Scrolledtree_BackGround.delete(row)
    
    log_to_console(gui, "Running background optimization diagnostic pass...")
    gui.TProgressbar1['value'] = 20
    gui.top.update_idletasks()
    
    all_processes = list(psutil.process_iter(['pid', 'name', 'memory_info']))
    gui.TProgressbar1['value'] = 60
    gui.top.update_idletasks()

    game_running = False

    for proc in all_processes:
        try:
            pinfo = proc.info
            p_name = pinfo['name']
            p_pid = pinfo['pid']
            
            if pinfo['memory_info']:
                p_mem = round(pinfo['memory_info'].rss / (1024 * 1024), 2)
            else:
                p_mem = 0.0
            
            if p_name.lower() in [g.lower() for g in installed_games_list]:
                game_running = True
            
            # Whitelist and Exception Processing Filters
            is_whitelisted = p_name.lower() in [w.lower() for w in system_whitelist]
            is_exception = p_name.lower() in [e.lower() for e in game_exceptions]
            
            if is_whitelisted or is_exception:
                scanned_safe_pool.append((p_name, p_pid, p_mem))
                gui.Scrolledtree_Safe.insert("", tk.END, text=p_name, values=(p_pid, f"{p_mem} MB"))
            else:
                scanned_junk_pool.append((p_name, p_pid, p_mem))
                gui.Scrolledtree_Junk.insert("", tk.END, text=p_name, values=(p_pid, f"{p_mem} MB"))
                gui.Scrolledtree_BackGround.insert("", tk.END, text=p_name, values=(p_pid, f"{p_mem} MB"))
                
        except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
            continue

    gui.TProgressbar1['value'] = 100
    log_to_console(gui, f"Scan Complete. Found {len(scanned_safe_pool)} Safe, {len(scanned_junk_pool)} Junk tasks.")
    
    if game_running and gui.che52.get() == 1:
        log_to_console(gui, "🎯 Game Mode Active! Launch verified. Executing background silent clean...")
        silent_game_clean(gui)

    gui.Scrolledtext_inspector.delete("1.0", tk.END)
    gui.Scrolledtext_inspector.insert(tk.END, "--- FOOTPRINT REPORT ---\n")
    gui.Scrolledtext_inspector.insert(tk.END, f"Total Apps Run: {len(all_processes)}\n")
    
    total_junk_ram = sum(item[2] for item in scanned_junk_pool)
    gui.Scrolledtext_inspector.insert(tk.END, f"Recoverable Ram: {round(total_junk_ram, 2)} MB\n\n")
    gui.Scrolledtext_inspector.insert(tk.END, "Click 'Auto-Clean' to free up system resources.")

# --------------------------------------------------------
# PROCESS TERMINATION & AUTOMATION ENGINES
# --------------------------------------------------------
def handle_clean(gui):
    '''Automatically purges background tasks that aren't on the whitelist.'''
    global scanned_junk_pool
    
    if not scanned_junk_pool:
        messagebox.showinfo("Optimization Engine", "No unneeded processes found. Run a Scan pass first!")
        return

    killed_count = 0
    recovered_ram = 0.0
    log_to_console(gui, f"Starting clean operation on {len(scanned_junk_pool)} tasks...")
    
    for proc_name, pid, ram in scanned_junk_pool:
        try:
            p = psutil.Process(pid)
            if p.name() == proc_name:
                p.kill()
                killed_count += 1
                recovered_ram += ram
        except Exception:
            continue
            
    log_to_console(gui, f"Success! Terminated {killed_count} processes. Freed {round(recovered_ram, 2)} MB RAM.")
    gui.TProgressbar1['value'] = 0
    handle_scan(gui) 

def silent_game_clean(gui):
    '''Quiet optimization handler deployed strictly for Game Mode environments.'''
    global scanned_junk_pool
    killed_count = 0
    
    for proc_name, pid, _ in scanned_junk_pool:
        try:
            p = psutil.Process(pid)
            if p.name() == proc_name:
                p.kill()
                killed_count += 1
        except Exception:
            continue
            
    if killed_count > 0:
        log_to_console(gui, f"⚡ Game Mode Sweep Finished. Closed {killed_count} background tasks silently.")

def handle_kill_selected(gui):
    '''Kills only the process manually selected by the user in the Junk tree view table.'''
    selected_item = gui.Scrolledtree_Junk.selection() or gui.Scrolledtree_BackGround.selection()
    
    if not selected_item:
        messagebox.showwarning("Target Registry", "Please click a process in a Background/Junk list to target.")
        return
        
    if gui.Scrolledtree_Junk.selection():
        tree = gui.Scrolledtree_Junk
    else:
        tree = gui.Scrolledtree_BackGround

    item_data = tree.item(selected_item[0])
    proc_name = item_data['text']
    pid = item_data['values'][0]
    
    try:
        p = psutil.Process(int(pid))
        p.kill()
        log_to_console(gui, f"Manually terminated custom hook: PID {pid} ({proc_name})")
        handle_scan(gui)
    except Exception as ex:
        messagebox.showerror("Target Registry Error", f"Could not end process {pid}: {str(ex)}")

def google_selected_process(gui):
    '''Grabs the process name selected in either box and opens a Google query for it.'''
    selected_item = gui.Scrolledtree_Junk.selection() or gui.Scrolledtree_Safe.selection() or gui.Scrolledtree_BackGround.selection()
    
    if not selected_item:
        messagebox.showinfo("Web Search", "Please click on a process name in either list first to search it.")
        return
        
    if gui.Scrolledtree_Junk.selection():
        tree = gui.Scrolledtree_Junk
    elif gui.Scrolledtree_Safe.selection():
        tree = gui.Scrolledtree_Safe
    else:
        tree = gui.Scrolledtree_BackGround
        
    item_data = tree.item(selected_item[0])
    proc_name = item_data['text']
    
    if proc_name:
        query = urllib.parse.quote(f"what is process {proc_name}")
        url = f"https://www.google.com/search?q={query}"
        log_to_console(gui, f"Launching Web browser query for footprint: '{proc_name}'")
        webbrowser.open(url)

# --------------------------------------------------------
# CUSTOM WHITELIST MODIFICATION SUBROUTINES
# --------------------------------------------------------
def add_whitelist_item(gui):
    new_app = gui.Entry_Whitelist.get().strip()
    
    if not new_app:
        return
        
    if new_app.lower() not in [item.lower() for item in system_whitelist]:
        system_whitelist.append(new_app)
        gui.Scrolledlist_WhiteLists.insert(tk.END, new_app)
        gui.Entry_Whitelist.delete(0, tk.END)
        log_to_console(gui, f"Whitelisted application entry point: '{new_app}'")
    else:
        messagebox.showinfo("Registry Info", "That process signature is already whitelisted.")

def remove_whitelist_item(gui):
    selected_idx = gui.Scrolledlist_WhiteLists.curselection()
    
    if not selected_idx:
        return
        
    item_name = gui.Scrolledlist_WhiteLists.get(selected_idx[0])
    protected_cores = ["explorer.exe", "taskmgr.exe", "python.exe", "cleaner.py"]
    
    if item_name.lower() in protected_cores:
        messagebox.showerror("System Core Protection", "Protected core system modules cannot be unmapped.")
        return
        
    system_whitelist.remove(item_name)
    gui.Scrolledlist_WhiteLists.delete(selected_idx[0])
    log_to_console(gui, f"Removed program signature from whitelist mapping: '{item_name}'")

# --------------------------------------------------------
# GAME DETECTION & EXCEPTION MANAGEMENT ENGINE
# --------------------------------------------------------
def handle_game_scan(gui):
    global installed_games_list
    log_to_console(gui, "Scanning system paths and registry targets for gaming profiles...")
    
    for row in gui.Scrolledtree_installed_games.get_children():
        gui.Scrolledtree_installed_games.delete(row)
        
    common_targets = [
        ("Steam Client", "steam.exe"),
        ("Epic Games Launcher", "EpicGamesLauncher.exe"),
        ("Riot Client", "RiotClientServices.exe"),
        ("EA Desktop", "EADesktop.exe")
    ]
    
    found_count = 0
    for name, binary in common_targets:
        if binary not in installed_games_list:
            installed_games_list.append(binary)
        gui.Scrolledtree_installed_games.insert("", tk.END, text=name, values=("DETECTED", binary))
        found_count += 1
        
    log_to_console(gui, f"Auto-Scan Complete. Linked ({found_count}) gaming applications.")

def handle_manual_game_add(gui):
    global installed_games_list
    file_path = filedialog.askopenfilename(title="Link Target Game Executable", filetypes=[("Executable Files", "*.exe")])
    
    if file_path:
        binary_name = os.path.basename(file_path)
        game_title = os.path.splitext(binary_name)[0].replace("_", " ").title()
        
        if binary_name.lower() not in [g.lower() for g in installed_games_list]:
            installed_games_list.append(binary_name)
            gui.Scrolledtree_installed_games.insert("", tk.END, text=game_title, values=("MANUAL", binary_name))
            log_to_console(gui, f"Successfully mapped tracking coordinates for game: {binary_name}")

def add_to_exceptions(gui):
    selected = gui.Scrolledtree_BackGround.selection() or gui.Scrolledtree_Junk.selection()
    
    if not selected:
        messagebox.showinfo("Exception Entry", "Select an active process signature from either Junk tree list first.")
        return
        
    if gui.Scrolledtree_BackGround.selection():
        tree = gui.Scrolledtree_BackGround
    else:
        tree = gui.Scrolledtree_Junk

    proc_name = tree.item(selected[0])['text']
    if proc_name and proc_name not in game_exceptions:
        game_exceptions.append(proc_name)
        refresh_exceptions_ui(gui)
        log_to_console(gui, f"Added tracking exception rules protection to target: {proc_name}")
        handle_scan(gui)

def remove_from_exceptions(gui):
    selected = gui.Scrolledlist_Exception.curselection()
    
    if not selected:
        return
        
    item_name = gui.Scrolledlist_Exception.get(selected[0])
    game_exceptions.remove(item_name)
    refresh_exceptions_ui(gui)
    log_to_console(gui, f"Exception filter trace dropped from: {item_name}")
    handle_scan(gui)

def refresh_exceptions_ui(gui):
    gui.Scrolledlist_Exception.delete(0, tk.END)
    for entry in game_exceptions:
        gui.Scrolledlist_Exception.insert(tk.END, entry)

# --------------------------------------------------------
# APPEARANCE STYLING & CORE CONFIGURATION STORAGE
# --------------------------------------------------------
def apply_theme_change(gui):
    theme = gui.theme_dropdown.get()
    
    if theme == "Dark Classic":
        gui.style.configure('.', background="#2b2b2b", foreground="#ffffff")
        gui.style.configure('TNotebook', background="#2b2b2b")
        gui.style.configure('TNotebook.Tab', background="#3e3e3e", foreground="#ffffff")
        gui.style.configure('Treeview', background="#1e1e1e", fieldbackground="#1e1e1e", foreground="#ffffff")
        gui.style.configure('Treeview.Heading', background="#3e3e3e", foreground="#ffffff")
        
        for tab in [gui.TNotebook_all_Dask, gui.TNotebook_all_white, gui.TNotebook_all_settings, gui.TNotebook_all_Games]:
            tab.configure(background="#2b2b2b")
            
        for widget in [gui.Label_header, gui.Label_Safe, gui.Label_Junk, gui.Label_inspector, gui.Label_console, gui.Label_Installed_Games, gui.Label_Theme, gui.Label_Exception, gui.Checkbutton_StartUp, gui.Checkbutton_live, gui.Checkbutton_Game_mode, gui.Label_BackJunk]:
            widget.configure(background="#2b2b2b", fg="#ffffff", activebackground="#2b2b2b", activeforeground="#ffffff")
            
        gui.Scrolledtext_console.configure(bg="#1e1e1e", fg="#00ff00")
        gui.Scrolledtext_inspector.configure(bg="#1e1e1e", fg="#ffffff")
        
    elif theme == "Light Modern":
        gui.style.configure('.', background="#f5f6fa", foreground="#2c3e50")
        gui.style.configure('TNotebook', background="#f5f6fa")
        gui.style.configure('TNotebook.Tab', background="#dcdde1", foreground="#2c3e50")
        gui.style.configure('Treeview', background="#ffffff", fieldbackground="#ffffff", foreground="#1b1b1b")
        gui.style.configure('Treeview.Heading', background="#dcdde1", foreground="#2c3e50")
        
        for tab in [gui.TNotebook_all_Dask, gui.TNotebook_all_white, gui.TNotebook_all_settings, gui.TNotebook_all_Games]:
            tab.configure(background="#f5f6fa")
            
        for widget in [gui.Label_header, gui.Label_Safe, gui.Label_Junk, gui.Label_inspector, gui.Label_console, gui.Label_Installed_Games, gui.Label_Theme, gui.Label_Exception, gui.Checkbutton_StartUp, gui.Checkbutton_live, gui.Checkbutton_Game_mode, gui.Label_BackJunk]:
            widget.configure(background="#f5f6fa", fg="#2c3e50", activebackground="#f5f6fa", activeforeground="#2c3e50")
            
        gui.Scrolledtext_console.configure(bg="#ffffff", fg="#1b1b1b")
        gui.Scrolledtext_inspector.configure(bg="#ffffff", fg="#1b1b1b")
        
    log_to_console(gui, f"Visual Theme configuration swapped to: {theme}")

def save_config_state(gui):
    payload = {
        "whitelist": system_whitelist,
        "exceptions": game_exceptions,
        "games_list": installed_games_list,
        "theme": gui.theme_dropdown.get(),
        "startup_sweep": gui.che73.get(),
        "live_refresh": gui.che49.get(),
        "game_mode": gui.che52.get()
    }
    try:
        with open(CONFIG_FILE, 'w') as f:
            json.dump(payload, f, indent=4)
        messagebox.showinfo("Config Manager", "Application configurations preserved dynamically.")
        
        global live_refresh_job
        if gui.che49.get() == 1 and not live_refresh_job:
            log_to_console(gui, "🔄 Real-time Live Refresh Active [5s Loops].")
            run_live_loop(gui)
        elif gui.che49.get() == 0 and live_refresh_job:
            root.after_cancel(live_refresh_job)
            live_refresh_job = None
            log_to_console(gui, "⏱️ Real-time Live Refresh Disabled.")
    except Exception as ex:
        messagebox.showerror("Config Error", f"Could not preserve configuration parameters: {str(ex)}")

def run_live_loop(gui):
    global live_refresh_job
    if gui.che49.get() == 1:
        handle_scan(gui)
        live_refresh_job = root.after(5000, lambda: run_live_loop(gui))

def load_persistent_config(gui):
    global system_whitelist, game_exceptions, installed_games_list, live_refresh_job
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r') as f:
                data = json.load(f)
            system_whitelist = data.get("whitelist", system_whitelist)
            game_exceptions = data.get("exceptions", game_exceptions)
            installed_games_list = data.get("games_list", [])
            gui.theme_dropdown.set(data.get("theme", "Dark Classic"))
            gui.che73.set(data.get("startup_sweep", 0))
            gui.che49.set(data.get("live_refresh", 0))
            gui.che52.set(data.get("game_mode", 0))
            
            if gui.che49.get() == 1 and not live_refresh_job:
                run_live_loop(gui)
            apply_theme_change(gui)
        except Exception:
            pass
            
    gui.Scrolledlist_WhiteLists.delete(0, tk.END)
    for entry in system_whitelist: 
        gui.Scrolledlist_WhiteLists.insert(tk.END, entry)
    refresh_exceptions_ui(gui)
    
    for row in gui.Scrolledtree_installed_games.get_children(): 
        gui.Scrolledtree_installed_games.delete(row)
        
    for game in installed_games_list:
        title = os.path.splitext(game)[0].replace("_", " ").title()
        gui.Scrolledtree_installed_games.insert("", tk.END, text=title, values=("SAVED", game))

if __name__ == '__main__':
    main()