#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jul 13, 2026 01:55:35 PM BST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import cleaner_support

_bgcolor = '#d9d9d9'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: cleaner_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'alt.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('alt')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1331x534+289+380")
        top.minsize(176, 1)
        top.maxsize(1924, 1050)
        top.resizable(1,  1)
        top.title("Task Master Pro")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.combobox = tk.StringVar()
        self.combobox.set('TCombobox')
        self.che52 = tk.IntVar()
        self.che49 = tk.IntVar()
        self.che73 = tk.IntVar()

        _style_code()
        self.TNotebook_all = ttk.Notebook(self.top)
        self.TNotebook_all.place(relx=0.0, rely=0.019, relheight=1.028
                , relwidth=1.007)
        self.TNotebook_all_Dask = tk.Frame(self.TNotebook_all)
        self.TNotebook_all.add(self.TNotebook_all_Dask, padding=3)
        self.TNotebook_all.tab(0, text="DaskBoard",compound="left",)
        self.TNotebook_all_Dask.configure(background="#d9d9d9")
        self.TNotebook_all_Dask.configure(highlightbackground="#d9d9d9")
        self.TNotebook_all_Dask.configure(highlightcolor="black")
        self.TNotebook_all_white = tk.Frame(self.TNotebook_all)
        self.TNotebook_all.add(self.TNotebook_all_white, padding=3)
        self.TNotebook_all.tab(1, text="Custom White List",compound="left",)
        self.TNotebook_all_white.configure(background="#d9d9d9")
        self.TNotebook_all_white.configure(highlightbackground="#d9d9d9")
        self.TNotebook_all_white.configure(highlightcolor="black")
        self.TNotebook_all_Games = tk.Frame(self.TNotebook_all)
        self.TNotebook_all.add(self.TNotebook_all_Games, padding=3)
        self.TNotebook_all.tab(2, text="game mode",compound="left",)
        self.TNotebook_all_Games.configure(background="#d9d9d9")
        self.TNotebook_all_Games.configure(highlightbackground="#d9d9d9")
        self.TNotebook_all_Games.configure(highlightcolor="black")
        self.TNotebook_all_settings = tk.Frame(self.TNotebook_all)
        self.TNotebook_all.add(self.TNotebook_all_settings, padding=3)
        self.TNotebook_all.tab(3, text="settings",compound="left",)
        self.TNotebook_all_settings.configure(background="#d9d9d9")
        self.TNotebook_all_settings.configure(highlightbackground="#d9d9d9")
        self.TNotebook_all_settings.configure(highlightcolor="black")

        self.Label_Junk = tk.Label(self.TNotebook_all_Dask)
        self.Label_Junk.place(relx=0.076, rely=0.45, height=32, width=311)
        self.Label_Junk.configure(activebackground="#d9d9d9")
        self.Label_Junk.configure(activeforeground="black")
        self.Label_Junk.configure(anchor='w')
        self.Label_Junk.configure(background="#d9d9d9")
        self.Label_Junk.configure(compound='left')
        self.Label_Junk.configure(disabledforeground="#a3a3a3")
        self.Label_Junk.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_Junk.configure(foreground="black")
        self.Label_Junk.configure(highlightbackground="#d9d9d9")
        self.Label_Junk.configure(highlightcolor="black")
        self.Label_Junk.configure(text='''Background Items/ Potential junk''')

        self.Scrolledtree_Safe = ScrolledTreeView(self.TNotebook_all_Dask)
        self.Scrolledtree_Safe.place(relx=0.03, rely=0.158, relheight=0.251
                , relwidth=0.341)
        self.Scrolledtree_Safe.configure(columns="Col1")
        # build_treeview_support starting.
        self.Scrolledtree_Safe.heading("#0",text="Tree")
        self.Scrolledtree_Safe.heading("#0",anchor="center")
        self.Scrolledtree_Safe.column("#0",width="213")
        self.Scrolledtree_Safe.column("#0",minwidth="20")
        self.Scrolledtree_Safe.column("#0",stretch="1")
        self.Scrolledtree_Safe.column("#0",anchor="w")
        self.Scrolledtree_Safe.heading("Col1",text="Col1")
        self.Scrolledtree_Safe.heading("Col1",anchor="center")
        self.Scrolledtree_Safe.column("Col1",width="213")
        self.Scrolledtree_Safe.column("Col1",minwidth="20")
        self.Scrolledtree_Safe.column("Col1",stretch="1")
        self.Scrolledtree_Safe.column("Col1",anchor="w")

        self.Label_inspector = tk.Label(self.TNotebook_all_Dask)
        self.Label_inspector.place(relx=0.747, rely=0.565, height=22, width=319)
        self.Label_inspector.configure(activebackground="#d9d9d9")
        self.Label_inspector.configure(activeforeground="black")
        self.Label_inspector.configure(anchor='w')
        self.Label_inspector.configure(background="#d9d9d9")
        self.Label_inspector.configure(compound='left')
        self.Label_inspector.configure(disabledforeground="#a3a3a3")
        self.Label_inspector.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_inspector.configure(foreground="black")
        self.Label_inspector.configure(highlightbackground="#d9d9d9")
        self.Label_inspector.configure(highlightcolor="black")
        self.Label_inspector.configure(text='''Process Inspector & Smart Search''')

        self.Label_Safe = tk.Label(self.TNotebook_all_Dask)
        self.Label_Safe.place(relx=0.12, rely=0.097, height=31, width=190)
        self.Label_Safe.configure(activebackground="#d9d9d9")
        self.Label_Safe.configure(activeforeground="black")
        self.Label_Safe.configure(anchor='w')
        self.Label_Safe.configure(background="#d9d9d9")
        self.Label_Safe.configure(compound='left')
        self.Label_Safe.configure(disabledforeground="#a3a3a3")
        self.Label_Safe.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_Safe.configure(foreground="black")
        self.Label_Safe.configure(highlightbackground="#d9d9d9")
        self.Label_Safe.configure(highlightcolor="black")
        self.Label_Safe.configure(text='''Verified/Safe Programs''')

        self.Label_console = tk.Label(self.TNotebook_all_Dask)
        self.Label_console.place(relx=0.792, rely=0.097, height=32, width=160)
        self.Label_console.configure(activebackground="#d9d9d9")
        self.Label_console.configure(activeforeground="black")
        self.Label_console.configure(anchor='w')
        self.Label_console.configure(background="#d9d9d9")
        self.Label_console.configure(compound='left')
        self.Label_console.configure(disabledforeground="#a3a3a3")
        self.Label_console.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_console.configure(foreground="black")
        self.Label_console.configure(highlightbackground="#d9d9d9")
        self.Label_console.configure(highlightcolor="black")
        self.Label_console.configure(text='''Activity Console''')

        self.Label_header = tk.Label(self.TNotebook_all_Dask)
        self.Label_header.place(relx=0.386, rely=0.0, height=31, width=332)
        self.Label_header.configure(activebackground="#d9d9d9")
        self.Label_header.configure(activeforeground="black")
        self.Label_header.configure(anchor='w')
        self.Label_header.configure(background="#d9d9d9")
        self.Label_header.configure(compound='left')
        self.Label_header.configure(disabledforeground="#a3a3a3")
        self.Label_header.configure(font="-family {Palatino Linotype} -size 14 -weight bold -slant italic")
        self.Label_header.configure(foreground="black")
        self.Label_header.configure(highlightbackground="#d9d9d9")
        self.Label_header.configure(highlightcolor="black")
        self.Label_header.configure(text='''Task Master Pro''')

        self.Scrolledtext_inspector = ScrolledText(self.TNotebook_all_Dask)
        self.Scrolledtext_inspector.place(relx=0.747, rely=0.624, relheight=0.279
                , relwidth=0.229)
        self.Scrolledtext_inspector.configure(background="white")
        self.Scrolledtext_inspector.configure(exportselection="0")
        self.Scrolledtext_inspector.configure(font="TkTextFont")
        self.Scrolledtext_inspector.configure(foreground="black")
        self.Scrolledtext_inspector.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext_inspector.configure(highlightcolor="black")
        self.Scrolledtext_inspector.configure(insertbackground="black")
        self.Scrolledtext_inspector.configure(insertborderwidth="3")
        self.Scrolledtext_inspector.configure(selectbackground="#d9d9d9")
        self.Scrolledtext_inspector.configure(selectforeground="black")
        self.Scrolledtext_inspector.configure(wrap="none")

        self.Scrolledtext_console = ScrolledText(self.TNotebook_all_Dask)
        self.Scrolledtext_console.place(relx=0.747, rely=0.156, relheight=0.339
                , relwidth=0.229)
        self.Scrolledtext_console.configure(background="white")
        self.Scrolledtext_console.configure(exportselection="0")
        self.Scrolledtext_console.configure(font="TkTextFont")
        self.Scrolledtext_console.configure(foreground="black")
        self.Scrolledtext_console.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext_console.configure(highlightcolor="black")
        self.Scrolledtext_console.configure(insertbackground="black")
        self.Scrolledtext_console.configure(insertborderwidth="3")
        self.Scrolledtext_console.configure(selectbackground="#d9d9d9")
        self.Scrolledtext_console.configure(selectforeground="black")
        self.Scrolledtext_console.configure(wrap="none")

        self.btn_scan = tk.Button(self.TNotebook_all_Dask)
        self.btn_scan.place(relx=0.471, rely=0.312, height=34, width=208)
        self.btn_scan.configure(activebackground="#d9d9d9")
        self.btn_scan.configure(activeforeground="black")
        self.btn_scan.configure(background="#d9d9d9")
        self.btn_scan.configure(compound='left')
        self.btn_scan.configure(disabledforeground="#a3a3a3")
        self.btn_scan.configure(font="-family {Palatino Linotype} -size 8 -weight bold -slant italic")
        self.btn_scan.configure(foreground="black")
        self.btn_scan.configure(highlightbackground="#d9d9d9")
        self.btn_scan.configure(highlightcolor="black")
        self.btn_scan.configure(text='''1.Scan Active Processes''')

        self.btn_clean = tk.Button(self.TNotebook_all_Dask)
        self.btn_clean.place(relx=0.471, rely=0.39, height=34, width=208)
        self.btn_clean.configure(activebackground="#d9d9d9")
        self.btn_clean.configure(activeforeground="black")
        self.btn_clean.configure(background="#d9d9d9")
        self.btn_clean.configure(compound='left')
        self.btn_clean.configure(disabledforeground="#a3a3a3")
        self.btn_clean.configure(font="-family {Palatino Linotype} -size 7 -weight bold -slant italic")
        self.btn_clean.configure(foreground="black")
        self.btn_clean.configure(highlightbackground="#d9d9d9")
        self.btn_clean.configure(highlightcolor="black")
        self.btn_clean.configure(text='''Auto-clean Unneeded Processes''')

        self.btn_kill = tk.Button(self.TNotebook_all_Dask)
        self.btn_kill.place(relx=0.471, rely=0.468, height=34, width=208)
        self.btn_kill.configure(activebackground="#d9d9d9")
        self.btn_kill.configure(activeforeground="black")
        self.btn_kill.configure(background="#d9d9d9")
        self.btn_kill.configure(compound='left')
        self.btn_kill.configure(disabledforeground="#a3a3a3")
        self.btn_kill.configure(font="-family {Palatino Linotype} -size 8 -weight bold -slant italic")
        self.btn_kill.configure(foreground="black")
        self.btn_kill.configure(highlightbackground="#d9d9d9")
        self.btn_kill.configure(highlightcolor="black")
        self.btn_kill.configure(text='''Kill Checked Elements Only''')

        self.btn_Google = tk.Button(self.TNotebook_all_Dask)
        self.btn_Google.place(relx=0.486, rely=0.546, height=34, width=178)
        self.btn_Google.configure(activebackground="#d9d9d9")
        self.btn_Google.configure(activeforeground="black")
        self.btn_Google.configure(background="#d9d9d9")
        self.btn_Google.configure(compound='left')
        self.btn_Google.configure(disabledforeground="#a3a3a3")
        self.btn_Google.configure(font="-family {Palatino Linotype} -size 8 -weight bold -slant italic")
        self.btn_Google.configure(foreground="black")
        self.btn_Google.configure(highlightbackground="#d9d9d9")
        self.btn_Google.configure(highlightcolor="black")
        self.btn_Google.configure(text='''Search Selected Process''')

        self.Label_waterMark = tk.Label(self.TNotebook_all_Dask)
        self.Label_waterMark.place(relx=0.0, rely=0.897, height=31, width=217)
        self.Label_waterMark.configure(activebackground="#d9d9d9")
        self.Label_waterMark.configure(activeforeground="black")
        self.Label_waterMark.configure(anchor='w')
        self.Label_waterMark.configure(background="#d9d9d9")
        self.Label_waterMark.configure(compound='left')
        self.Label_waterMark.configure(disabledforeground="#a3a3a3")
        self.Label_waterMark.configure(foreground="#e1e1e1")
        self.Label_waterMark.configure(highlightbackground="#d9d9d9")
        self.Label_waterMark.configure(highlightcolor="#a0a0a0")
        self.Label_waterMark.configure(text='''created by Ginges3Dprints''')

        self.TProgressbar1 = ttk.Progressbar(self.TNotebook_all_Dask)
        self.TProgressbar1.place(relx=0.478, rely=0.273, relwidth=0.143
                , relheight=0.0, height=18)
        self.TProgressbar1.configure(length="192")

        self.Scrolledtree_Junk = ScrolledTreeView(self.TNotebook_all_Dask)
        self.Scrolledtree_Junk.place(relx=0.03, rely=0.528, relheight=0.253
                , relwidth=0.348)
        self.Scrolledtree_Junk.configure(columns="Col1")
        # build_treeview_support starting.
        self.Scrolledtree_Junk.heading("#0",text="Tree")
        self.Scrolledtree_Junk.heading("#0",anchor="center")
        self.Scrolledtree_Junk.column("#0",width="218")
        self.Scrolledtree_Junk.column("#0",minwidth="20")
        self.Scrolledtree_Junk.column("#0",stretch="1")
        self.Scrolledtree_Junk.column("#0",anchor="w")
        self.Scrolledtree_Junk.heading("Col1",text="Col1")
        self.Scrolledtree_Junk.heading("Col1",anchor="center")
        self.Scrolledtree_Junk.column("Col1",width="218")
        self.Scrolledtree_Junk.column("Col1",minwidth="20")
        self.Scrolledtree_Junk.column("Col1",stretch="1")
        self.Scrolledtree_Junk.column("Col1",anchor="w")

        self.Button_Remove = tk.Button(self.TNotebook_all_white)
        self.Button_Remove.place(relx=0.882, rely=0.858, height=34, width=118)
        self.Button_Remove.configure(activebackground="#d9d9d9")
        self.Button_Remove.configure(activeforeground="black")
        self.Button_Remove.configure(background="#d9d9d9")
        self.Button_Remove.configure(compound='left')
        self.Button_Remove.configure(disabledforeground="#a3a3a3")
        self.Button_Remove.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Button_Remove.configure(foreground="black")
        self.Button_Remove.configure(highlightbackground="#d9d9d9")
        self.Button_Remove.configure(highlightcolor="black")
        self.Button_Remove.configure(text='''Remove''')

        self.Button_Add = tk.Button(self.TNotebook_all_white)
        self.Button_Add.place(relx=0.882, rely=0.78, height=34, width=118)
        self.Button_Add.configure(activebackground="#d9d9d9")
        self.Button_Add.configure(activeforeground="black")
        self.Button_Add.configure(background="#d9d9d9")
        self.Button_Add.configure(compound='left')
        self.Button_Add.configure(disabledforeground="#a3a3a3")
        self.Button_Add.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Button_Add.configure(foreground="black")
        self.Button_Add.configure(highlightbackground="#d9d9d9")
        self.Button_Add.configure(highlightcolor="black")
        self.Button_Add.configure(text='''Add''')

        self.Entry_Whitelist = tk.Entry(self.TNotebook_all_white)
        self.Entry_Whitelist.place(relx=0.008, rely=0.411, height=26
                , relwidth=0.339)
        self.Entry_Whitelist.configure(background="#d9d9d9")
        self.Entry_Whitelist.configure(disabledforeground="#a3a3a3")
        self.Entry_Whitelist.configure(exportselection="0")
        self.Entry_Whitelist.configure(font="TkFixedFont")
        self.Entry_Whitelist.configure(foreground="black")
        self.Entry_Whitelist.configure(highlightbackground="#d9d9d9")
        self.Entry_Whitelist.configure(highlightcolor="black")
        self.Entry_Whitelist.configure(insertbackground="black")
        self.Entry_Whitelist.configure(selectbackground="#d9d9d9")
        self.Entry_Whitelist.configure(selectforeground="black")

        self.Scrolledlist_WhiteLists = ScrolledListBox(self.TNotebook_all_white)
        self.Scrolledlist_WhiteLists.place(relx=0.007, rely=0.078, relheight=0.31
                , relwidth=0.469)
        self.Scrolledlist_WhiteLists.configure(background="white")
        self.Scrolledlist_WhiteLists.configure(cursor="xterm")
        self.Scrolledlist_WhiteLists.configure(disabledforeground="#a3a3a3")
        self.Scrolledlist_WhiteLists.configure(exportselection="0")
        self.Scrolledlist_WhiteLists.configure(font="TkFixedFont")
        self.Scrolledlist_WhiteLists.configure(foreground="black")
        self.Scrolledlist_WhiteLists.configure(highlightbackground="#d9d9d9")
        self.Scrolledlist_WhiteLists.configure(highlightcolor="#919191")
        self.Scrolledlist_WhiteLists.configure(selectbackground="#d9d9d9")
        self.Scrolledlist_WhiteLists.configure(selectforeground="black")

        self.Label_Installed_Games = tk.Label(self.TNotebook_all_Games)
        self.Label_Installed_Games.place(relx=0.129, rely=0.119, height=31
                , width=149)
        self.Label_Installed_Games.configure(activebackground="#d9d9d9")
        self.Label_Installed_Games.configure(activeforeground="black")
        self.Label_Installed_Games.configure(anchor='w')
        self.Label_Installed_Games.configure(background="#d9d9d9")
        self.Label_Installed_Games.configure(compound='left')
        self.Label_Installed_Games.configure(disabledforeground="#a3a3a3")
        self.Label_Installed_Games.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_Installed_Games.configure(foreground="black")
        self.Label_Installed_Games.configure(highlightbackground="#d9d9d9")
        self.Label_Installed_Games.configure(highlightcolor="black")
        self.Label_Installed_Games.configure(text='''Installed Games''')

        self.Checkbutton_Game_mode = tk.Checkbutton(self.TNotebook_all_Games)
        self.Checkbutton_Game_mode.place(relx=0.439, rely=0.119, relheight=0.072
                , relwidth=0.158)
        self.Checkbutton_Game_mode.configure(activebackground="#d9d9d9")
        self.Checkbutton_Game_mode.configure(activeforeground="black")
        self.Checkbutton_Game_mode.configure(anchor='w')
        self.Checkbutton_Game_mode.configure(background="#d9d9d9")
        self.Checkbutton_Game_mode.configure(compound='left')
        self.Checkbutton_Game_mode.configure(disabledforeground="#a3a3a3")
        self.Checkbutton_Game_mode.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Checkbutton_Game_mode.configure(foreground="black")
        self.Checkbutton_Game_mode.configure(highlightbackground="#d9d9d9")
        self.Checkbutton_Game_mode.configure(highlightcolor="black")
        self.Checkbutton_Game_mode.configure(justify='left')
        self.Checkbutton_Game_mode.configure(text='''Enable Game Mode''')
        self.Checkbutton_Game_mode.configure(variable=self.che52)

        self.btn_Scan_Games = tk.Button(self.TNotebook_all_Games)
        self.btn_Scan_Games.place(relx=0.852, rely=0.76, height=44, width=168)
        self.btn_Scan_Games.configure(activebackground="#d9d9d9")
        self.btn_Scan_Games.configure(activeforeground="black")
        self.btn_Scan_Games.configure(background="#d9d9d9")
        self.btn_Scan_Games.configure(compound='left')
        self.btn_Scan_Games.configure(disabledforeground="#a3a3a3")
        self.btn_Scan_Games.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.btn_Scan_Games.configure(foreground="black")
        self.btn_Scan_Games.configure(highlightbackground="#d9d9d9")
        self.btn_Scan_Games.configure(highlightcolor="black")
        self.btn_Scan_Games.configure(text='''Auto-scan games''')

        self.btn_Man_Games = tk.Button(self.TNotebook_all_Games)
        self.btn_Man_Games.place(relx=0.852, rely=0.858, height=44, width=168)
        self.btn_Man_Games.configure(activebackground="#d9d9d9")
        self.btn_Man_Games.configure(activeforeground="black")
        self.btn_Man_Games.configure(background="#d9d9d9")
        self.btn_Man_Games.configure(compound='left')
        self.btn_Man_Games.configure(disabledforeground="#a3a3a3")
        self.btn_Man_Games.configure(font="-family {Palatino Linotype} -size 8 -weight bold -slant italic")
        self.btn_Man_Games.configure(foreground="black")
        self.btn_Man_Games.configure(highlightbackground="#d9d9d9")
        self.btn_Man_Games.configure(highlightcolor="black")
        self.btn_Man_Games.configure(text='''Manually add games''')

        self.Scrolledtree_installed_games = ScrolledTreeView(self.TNotebook_all_Games)
        self.Scrolledtree_installed_games.place(relx=0.023, rely=0.175
                , relheight=0.331, relwidth=0.339)
        self.Scrolledtree_installed_games.configure(columns="Col1")
        # build_treeview_support starting.
        self.Scrolledtree_installed_games.heading("#0",text="Tree")
        self.Scrolledtree_installed_games.heading("#0",anchor="center")
        self.Scrolledtree_installed_games.column("#0",width="211")
        self.Scrolledtree_installed_games.column("#0",minwidth="20")
        self.Scrolledtree_installed_games.column("#0",stretch="1")
        self.Scrolledtree_installed_games.column("#0",anchor="w")
        self.Scrolledtree_installed_games.heading("Col1",text="Col1")
        self.Scrolledtree_installed_games.heading("Col1",anchor="center")
        self.Scrolledtree_installed_games.column("Col1",width="212")
        self.Scrolledtree_installed_games.column("Col1",minwidth="20")
        self.Scrolledtree_installed_games.column("Col1",stretch="1")
        self.Scrolledtree_installed_games.column("Col1",anchor="w")

        self.Scrolledlist_Exception = ScrolledListBox(self.TNotebook_all_Games)
        self.Scrolledlist_Exception.place(relx=0.688, rely=0.175, relheight=0.287
                , relwidth=0.232)
        self.Scrolledlist_Exception.configure(background="white")
        self.Scrolledlist_Exception.configure(cursor="xterm")
        self.Scrolledlist_Exception.configure(disabledforeground="#a3a3a3")
        self.Scrolledlist_Exception.configure(exportselection="0")
        self.Scrolledlist_Exception.configure(font="TkFixedFont")
        self.Scrolledlist_Exception.configure(foreground="black")
        self.Scrolledlist_Exception.configure(highlightbackground="#d9d9d9")
        self.Scrolledlist_Exception.configure(highlightcolor="#919191")
        self.Scrolledlist_Exception.configure(selectbackground="#d9d9d9")
        self.Scrolledlist_Exception.configure(selectforeground="black")

        self.Label_Exception = tk.Label(self.TNotebook_all_Games)
        self.Label_Exception.place(relx=0.755, rely=0.117, height=31, width=137)
        self.Label_Exception.configure(activebackground="#d9d9d9")
        self.Label_Exception.configure(activeforeground="black")
        self.Label_Exception.configure(anchor='w')
        self.Label_Exception.configure(background="#d9d9d9")
        self.Label_Exception.configure(compound='left')
        self.Label_Exception.configure(disabledforeground="#a3a3a3")
        self.Label_Exception.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_Exception.configure(foreground="black")
        self.Label_Exception.configure(highlightbackground="#d9d9d9")
        self.Label_Exception.configure(highlightcolor="black")
        self.Label_Exception.configure(text='''Exception List''')

        self.btn_Exception = tk.Button(self.TNotebook_all_Games)
        self.btn_Exception.place(relx=0.74, rely=0.468, height=34, width=168)
        self.btn_Exception.configure(activebackground="#d9d9d9")
        self.btn_Exception.configure(activeforeground="black")
        self.btn_Exception.configure(background="#d9d9d9")
        self.btn_Exception.configure(compound='left')
        self.btn_Exception.configure(disabledforeground="#a3a3a3")
        self.btn_Exception.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.btn_Exception.configure(foreground="black")
        self.btn_Exception.configure(highlightbackground="#d9d9d9")
        self.btn_Exception.configure(highlightcolor="black")
        self.btn_Exception.configure(text='''Add Exception''')

        self.btn_RemoveException = tk.Button(self.TNotebook_all_Games)
        self.btn_RemoveException.place(relx=0.74, rely=0.546, height=34
                , width=168)
        self.btn_RemoveException.configure(activebackground="#d9d9d9")
        self.btn_RemoveException.configure(activeforeground="black")
        self.btn_RemoveException.configure(background="#d9d9d9")
        self.btn_RemoveException.configure(compound='left')
        self.btn_RemoveException.configure(disabledforeground="#a3a3a3")
        self.btn_RemoveException.configure(font="-family {Palatino Linotype} -size 8 -weight bold -slant italic")
        self.btn_RemoveException.configure(foreground="black")
        self.btn_RemoveException.configure(highlightbackground="#d9d9d9")
        self.btn_RemoveException.configure(highlightcolor="black")
        self.btn_RemoveException.configure(text='''Remove Exception''')

        self.Label_BackJunk = tk.Label(self.TNotebook_all_Games)
        self.Label_BackJunk.place(relx=0.067, rely=0.546, height=31, width=306)
        self.Label_BackJunk.configure(activebackground="#d9d9d9")
        self.Label_BackJunk.configure(activeforeground="black")
        self.Label_BackJunk.configure(anchor='w')
        self.Label_BackJunk.configure(background="#d9d9d9")
        self.Label_BackJunk.configure(compound='left')
        self.Label_BackJunk.configure(disabledforeground="#a3a3a3")
        self.Label_BackJunk.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_BackJunk.configure(foreground="black")
        self.Label_BackJunk.configure(highlightbackground="#d9d9d9")
        self.Label_BackJunk.configure(highlightcolor="black")
        self.Label_BackJunk.configure(text='''Background Items/ Potential junk''')

        self.Scrolledtree_BackGround = ScrolledTreeView(self.TNotebook_all_Games)
        self.Scrolledtree_BackGround.place(relx=0.022, rely=0.604, relheight=0.24
                , relwidth=0.337)
        self.Scrolledtree_BackGround.configure(columns="Col1")
        # build_treeview_support starting.
        self.Scrolledtree_BackGround.heading("#0",text="Tree")
        self.Scrolledtree_BackGround.heading("#0",anchor="center")
        self.Scrolledtree_BackGround.column("#0",width="210")
        self.Scrolledtree_BackGround.column("#0",minwidth="20")
        self.Scrolledtree_BackGround.column("#0",stretch="1")
        self.Scrolledtree_BackGround.column("#0",anchor="w")
        self.Scrolledtree_BackGround.heading("Col1",text="Col1")
        self.Scrolledtree_BackGround.heading("Col1",anchor="center")
        self.Scrolledtree_BackGround.column("Col1",width="211")
        self.Scrolledtree_BackGround.column("Col1",minwidth="20")
        self.Scrolledtree_BackGround.column("Col1",stretch="1")
        self.Scrolledtree_BackGround.column("Col1",anchor="w")

        self.btn_scanbackground = tk.Button(self.TNotebook_all_Games)
        self.btn_scanbackground.place(relx=0.724, rely=0.799, height=44
                , width=168)
        self.btn_scanbackground.configure(activebackground="#d9d9d9")
        self.btn_scanbackground.configure(activeforeground="black")
        self.btn_scanbackground.configure(background="#d9d9d9")
        self.btn_scanbackground.configure(compound='left')
        self.btn_scanbackground.configure(disabledforeground="#a3a3a3")
        self.btn_scanbackground.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.btn_scanbackground.configure(foreground="black")
        self.btn_scanbackground.configure(highlightbackground="#d9d9d9")
        self.btn_scanbackground.configure(highlightcolor="black")
        self.btn_scanbackground.configure(text='''Scan Background''')

        self.theme_dropdown = ttk.Combobox(self.TNotebook_all_settings)
        self.theme_dropdown.place(relx=0.424, rely=0.119, relheight=0.06
                , relwidth=0.259)
        self.theme_dropdown.configure(exportselection="0")
        self.theme_dropdown.configure(textvariable=self.combobox)

        self.Label_Theme = tk.Label(self.TNotebook_all_settings)
        self.Label_Theme.place(relx=0.5, rely=0.058, height=32, width=136)
        self.Label_Theme.configure(activebackground="#d9d9d9")
        self.Label_Theme.configure(activeforeground="black")
        self.Label_Theme.configure(anchor='w')
        self.Label_Theme.configure(background="#d9d9d9")
        self.Label_Theme.configure(compound='left')
        self.Label_Theme.configure(disabledforeground="#a3a3a3")
        self.Label_Theme.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Label_Theme.configure(foreground="black")
        self.Label_Theme.configure(highlightbackground="#d9d9d9")
        self.Label_Theme.configure(highlightcolor="black")
        self.Label_Theme.configure(text='''Theme Selctor''')

        self.btn_undo = tk.Button(self.TNotebook_all_settings)
        self.btn_undo.place(relx=0.882, rely=0.877, height=34, width=128)
        self.btn_undo.configure(activebackground="#d9d9d9")
        self.btn_undo.configure(activeforeground="black")
        self.btn_undo.configure(background="#d9d9d9")
        self.btn_undo.configure(compound='left')
        self.btn_undo.configure(disabledforeground="#a3a3a3")
        self.btn_undo.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.btn_undo.configure(foreground="black")
        self.btn_undo.configure(highlightbackground="#d9d9d9")
        self.btn_undo.configure(highlightcolor="black")
        self.btn_undo.configure(text='''undo''')

        self.btn_Apply = tk.Button(self.TNotebook_all_settings)
        self.btn_Apply.place(relx=0.882, rely=0.799, height=34, width=128)
        self.btn_Apply.configure(activebackground="#d9d9d9")
        self.btn_Apply.configure(activeforeground="black")
        self.btn_Apply.configure(background="#d9d9d9")
        self.btn_Apply.configure(compound='left')
        self.btn_Apply.configure(disabledforeground="#a3a3a3")
        self.btn_Apply.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.btn_Apply.configure(foreground="black")
        self.btn_Apply.configure(highlightbackground="#d9d9d9")
        self.btn_Apply.configure(highlightcolor="black")
        self.btn_Apply.configure(text='''Save''')

        self.Checkbutton_live = tk.Checkbutton(self.TNotebook_all_settings)
        self.Checkbutton_live.place(relx=0.03, rely=0.175, relheight=0.074
                , relwidth=0.18)
        self.Checkbutton_live.configure(activebackground="#d9d9d9")
        self.Checkbutton_live.configure(activeforeground="black")
        self.Checkbutton_live.configure(anchor='w')
        self.Checkbutton_live.configure(background="#d9d9d9")
        self.Checkbutton_live.configure(compound='left')
        self.Checkbutton_live.configure(disabledforeground="#a3a3a3")
        self.Checkbutton_live.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Checkbutton_live.configure(foreground="black")
        self.Checkbutton_live.configure(highlightbackground="#d9d9d9")
        self.Checkbutton_live.configure(highlightcolor="black")
        self.Checkbutton_live.configure(justify='left')
        self.Checkbutton_live.configure(text='''Real-time Live Refresh''')
        self.Checkbutton_live.configure(variable=self.che49)

        self.Checkbutton_StartUp = tk.Checkbutton(self.TNotebook_all_settings)
        self.Checkbutton_StartUp.place(relx=0.03, rely=0.119, relheight=0.072
                , relwidth=0.151)
        self.Checkbutton_StartUp.configure(activebackground="#d9d9d9")
        self.Checkbutton_StartUp.configure(activeforeground="black")
        self.Checkbutton_StartUp.configure(anchor='w')
        self.Checkbutton_StartUp.configure(background="#d9d9d9")
        self.Checkbutton_StartUp.configure(compound='left')
        self.Checkbutton_StartUp.configure(disabledforeground="#a3a3a3")
        self.Checkbutton_StartUp.configure(font="-family {Palatino Linotype} -size 10 -weight bold -slant italic")
        self.Checkbutton_StartUp.configure(foreground="black")
        self.Checkbutton_StartUp.configure(highlightbackground="#d9d9d9")
        self.Checkbutton_StartUp.configure(highlightcolor="black")
        self.Checkbutton_StartUp.configure(justify='left')
        self.Checkbutton_StartUp.configure(text='''Enable on start up''')
        self.Checkbutton_StartUp.configure(variable=self.che73)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    cleaner_support.main()

if __name__ == '__main__':
    cleaner_support.main()